# Configurações específicas para o ambiente 'dev' (local)
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sansys_database
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update